- name: perform system upgrade
  apt:
    upgrade: dist
    autoremove: yes
    force_apt_get: yes
  become: yes

- name: install useful tools
  package:
    name: "{{ item }}"
  with_items:
    - htop
    - vim
  become: yes
