---
- hosts: all
  become: false
  gather_facts: false
  vars_files:
    - ../config.yml
  pre_tasks:
    - name: install Python2
      raw: sudo apt-get -y install python

    - name: gather facts
      setup:
  roles:
    - system
    - openvpn
